/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#ccbeff',
        'on-primary-fixed': '#25005a',
        'on-surface': '#e4e1e9',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed': '#1e0e4e',
        'on-tertiary-container': '#ffe0cd',
        'inverse-surface': '#e4e1e9',
        'surface-container-low': '#1b1b20',
        'surface-container-lowest': '#0e0e13',
        background: '#131318',
        'on-secondary-fixed-variant': '#4a3d7c',
        'on-primary': '#3f008e',
        'primary-container': '#7c3aed',
        'surface-card': '#111118',
        'on-tertiary-fixed': '#301400',
        'outline-variant': '#4a4455',
        'on-surface-variant': '#ccc3d8',
        'border-muted': '#1E1E2E',
        'surface-bright': '#39383e',
        'primary-fixed-dim': '#d2bbff',
        'on-secondary-container': '#baabf3',
        'inverse-primary': '#732ee4',
        success: '#10B981',
        'surface-dim': '#131318',
        'text-primary': '#F8F8FF',
        outline: '#958da1',
        'primary-fixed': '#eaddff',
        'surface-container-highest': '#35343a',
        'secondary-container': '#4a3d7c',
        'on-primary-fixed-variant': '#5a00c6',
        'on-background': '#e4e1e9',
        'tertiary-fixed': '#ffdcc6',
        'on-tertiary-fixed-variant': '#713700',
        surface: '#131318',
        'surface-tint': '#d2bbff',
        'secondary-fixed': '#e7deff',
        'surface-variant': '#35343a',
        tertiary: '#ffb784',
        'inverse-on-surface': '#303036',
        error: '#ffb4ab',
        'surface-container': '#1f1f25',
        'on-error': '#690005',
        'on-primary-container': '#ede0ff',
        'error-container': '#93000a',
        'text-secondary': '#8B8BA7',
        'on-secondary': '#332664',
        primary: '#d2bbff',
        'tertiary-fixed-dim': '#ffb784',
        'secondary-fixed-dim': '#ccbeff',
        'on-tertiary': '#4f2500',
        'surface-container-high': '#2a292f',
        warning: '#F59E0B',
        'tertiary-container': '#a15100',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '32px',
        gutter: '24px',
        'margin-desktop': '64px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        'stack-md': '16px',
      },
      fontFamily: {
        'display-xl-mobile': ['Playfair Display'],
        'display-xl': ['Playfair Display'],
        'label-mono': ['JetBrains Mono'],
        'headline-lg': ['Playfair Display'],
        'body-lg': ['Inter'],
        'label-caps': ['Inter'],
        'headline-md': ['Playfair Display'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'display-xl-mobile': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-mono': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
